development:
  adapter: postgresql
  encoding: unicode
  database: decipher_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: decipher_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: decipher_production
  pool: 5
  username:
  password:
